server:
  port: 8080

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 724811
      url: jdbc:mysql://localhost:3306/im_demo
      username: root

logging:
  config: classpath:log4j2.xml

